### ISSUE TITLE
多次使用权限问题

### ISSUE THREAD

**Issue by nghaiker** [GlobeFishNG/setup-cloud-cli#1]
例如：
```yaml
steps:
  - name: Run build.sh Script
      run: |
        ./scripts/build.sh
      timeout-minutes: 35

  - name: setup default profile
    uses: GlobeFishNG/setup-cloud-cli@v0.0.3
    with:
      profile: default
  - name: upload client to default
    run: |
      ./scripts/upload/default.sh app

  # 下面这个设置就会出错
  - name: setup aliyun profile
    uses: GlobeFishNG/setup-cloud-cli@v0.0.3
    with:
      profile: aliyun

  - name: upload client to aliyun
    run: |
      ./scripts/upload/aliyun.sh app
```

 报错内容为
![image](https://user-images.githubusercontent.com/80658140/153117400-4b2536bf-04a3-435d-b5c9-6a9c4ced2f7a.png)
原因，设置 profile=default之后就aws role 已经修改，再次使用setup-cloud-cli时，就权限不对了。当然我们可以把使用顺序更换问题可以暂时解决。但是问题可以在可预见的未来就会重现（PreSugre美国送检环境）。
